server:
  port: 9090

spring:
  application:
    name: recipe-service
  datasource:
    url: jdbc:h2:mem:recipe_db
    driverClassName: org.h2.Driver
    username: recipe
    password: recipe
  h2:
    console:
      enabled: true

springfox:
  documentation:
    swagger-ui:
      enabled: true